carpentry: epiverse-trace
title: Real-time analysis and forecasting for outbreak analytics with R
created: ~
keywords: forecasts, epidemic models, interventions
life_cycle: pre-alpha
license: CC-BY 4.0
source: https://github.com/epiverse-trace/tutorials-middle
branch: main
contact: andree.valle-campos@lshtm.ac.uk
episodes:
- delays-access.Rmd
- quantify-transmissibility.Rmd
- delays-functions.Rmd
- create-forecast.Rmd
- severity-static.Rmd
- superspreading-estimate.Rmd
- superspreading-simulate.Rmd
learners: ~
instructors: ~
profiles: ~
varnish: epiverse-trace/varnish@epiversetheme
sandpaper: epiverse-trace/sandpaper@patch-renv-github-bug
lang: es
